/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects. It is included here so
// the foundation has a complete editor-ready TypeScript surface from the start.
